DATABASE:
  URI : "bolt://localhost:7687"
  USER : "neo4j"
  PASSWORD : "healthcare"  # Change this to your Neo4j database password
  DBNAME : "neo4j"
  CONTENTS:
  - "Hospital"
  - "SA2"

VISUALIZATION:
  COLORS:
    Hospital: "#faca2b"
    SA2: "#0068c9"
    Edges:
    # Green for closest, orange for mid, red for far
      close: "#09ab3b"
      mid: "#ff822B"
      far: "#ff2b2b"
  COLUMN_NAMING:
    HOSPITALS:
      hospital_name: "Hospital Name"
      address: "Address"
      latitude: "Latitude"
      longitude: "Longitude"
      phone_number: "Phone Number"
      website: "Website"
      beds: "Number of Beds"
      description: "Description"
      id: "ID"
      lhn: "Local Health Network"
      phn: "Primary Health Network"
      postcode: "Postcode"
      sector: "Sector"
      state: "State"
      suburb: "Suburb"
    SA2:
      sa2_name: "SA2 Name"
      area: "Area"
      id: "SA2 code"
      pop_density: "Population Density"
      pop_percentage: "Population Percentage"
      population: "Population"

MESSAGES:
  ERRORS:
    START: Error while starting the application, have you started the Neo4j database?
    QUERY: Error while querying the database. Please check the query and try again.

DEFAULT_QUERY: "MATCH (n)-[r]->(m) RETURN n, r, m"

EXAMPLE_QUERIES:
  show_edges:
    query: "MATCH (n)-[r]->(m) RETURN n, r, m"
    description: "Show all edges in the database"
    key: "show_edges"
    limit: True
  not_accessible:
    query: "
      MATCH (sa2:SA2)
      WHERE NOT EXISTS {
        MATCH (sa2)<-[:REACHABLE_VIA {accessible: True}]-(:Hospital)
      }
      RETURN sa2
      "
    description: "Show SA2 areas with no accessible hospitals (distance > 30 minutes)"
    key: "not_accessible"
    limit: True
  population_to_beds:
    query: "
      MATCH (sa2:SA2)<-[:REACHABLE_VIA]-(h:Hospital)
      WITH sa2.sa2_name AS SA2Area, sa2.population AS Population, 
          CASE
            WHEN h.beds CONTAINS '<' THEN toInteger(REPLACE(h.beds, '<', ''))
            WHEN h.beds CONTAINS '>' THEN toInteger(REPLACE(h.beds, '>', ''))
            ELSE toInteger(h.beds)
          END AS Beds
      WITH SA2Area, Population, SUM(Beds) AS TotalBeds
      RETURN SA2Area, Population, TotalBeds, 
            CASE
              WHEN TotalBeds = 0 THEN NULL
              ELSE Population / TotalBeds
            END AS Ratio
      "
    description: "Show the relation between population and number of beds in hospitals in SA2 areas"
    key: "population_to_beds"
    limit: True
  show_accessible:
    query: "MATCH (n:Hospital)-[r:REACHABLE_VIA {accessible: True}]->(m:SA2) RETURN n, r, m"
    description: "Show all hospitals that are accessible from SA2s"
    key: "show_accessible_hospitals"
    limit: True
  most_accessible:
    query: "
      MATCH (sa2:SA2)<-[:REACHABLE_VIA {accessible: True}]-(h:Hospital)
      WITH h.state AS State, COUNT(DISTINCT h) AS AccessibleHospitals
      RETURN State, AccessibleHospitals
      ORDER BY AccessibleHospitals DESC
      "
    description: "Show the states with the most accessible hospitals"
    key: "most_accessible"
    limit: True
  least_hospitals:
    query: "
      MATCH (sa2:SA2)<-[:REACHABLE_VIA]-(h:Hospital)
      WITH sa2.sa2_name AS SA2Area, COUNT(DISTINCT h) AS HospitalCount
      ORDER BY HospitalCount ASC
      RETURN SA2Area, HospitalCount
      "
    description: "SA2 areas with the least hospitals"
    key: "least_hospitals"
    limit: True
  distance_ratio:
    query: "
      MATCH (sa2:SA2)<-[r:REACHABLE_VIA]-(h:Hospital)
      WITH sa2, h, r.distance_time AS Distance
      ORDER BY sa2.sa2_name, Distance
      WITH sa2, COLLECT(Distance) AS Distances
      RETURN sa2.sa2_name AS SA2Area,
            HEAD(Distances) AS ClosestHospitalDistance,
            LAST(Distances) AS FurthestHospitalDistance,
            CASE
              WHEN HEAD(Distances) = 0 THEN 'Undefined'
              ELSE (TOFLOAT(LAST(Distances)) / TOFLOAT(HEAD(Distances)))
            END AS DistanceRatio
      ORDER BY DistanceRatio DESC
      "
    description: "Ratio of distance between closest and furthest hospital in SA2 areas"
    key: "distance_ratio"
    limit: True
